name: Build iOS App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Package
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          set -e

          # libarchive is consumed by the LLVM-On-iOS toolchain build.
          brew install libarchive

      - name: Build Jailed
        timeout-minutes: 1200
        run: |
          set -e

          # Build the project (jailed)
          CHECK_DEPS=0 make jailed

      - name: Upload Jailed
        uses: actions/upload-artifact@v4
        with:
          name: emexDE.ipa
          path: emexDE.ipa
